import type { H3Event } from 'h3';

export const constItemsCountry = (event: H3Event) => {
  return [
    {
      name: 'Andorra',
      iso: 'AD',
      dial_code: '+376',
      flag_icon: '/flag-icons/ad.svg',
    },
    {
      name: 'United Arab Emirates',
      iso: 'AE',
      dial_code: '+971',
      flag_icon: '/flag-icons/ae.svg',
    },
    {
      name: 'Afghanistan',
      iso: 'AF',
      dial_code: '+93',
      flag_icon: '/flag-icons/af.svg',
    },
    {
      name: 'Antigua and Barbuda',
      iso: 'AG',
      dial_code: '+1',
      flag_icon: '/flag-icons/ag.svg',
    },
    {
      name: 'Anguilla',
      iso: 'AI',
      dial_code: '+1',
      flag_icon: '/flag-icons/ai.svg',
    },
    {
      name: 'Albania',
      iso: 'AL',
      dial_code: '+355',
      flag_icon: '/flag-icons/al.svg',
    },
    {
      name: 'Armenia',
      iso: 'AM',
      dial_code: '+374',
      flag_icon: '/flag-icons/am.svg',
    },
    {
      name: 'Angola',
      iso: 'AO',
      dial_code: '+244',
      flag_icon: '/flag-icons/ao.svg',
    },
    {
      name: 'Antarctica',
      iso: 'AQ',
      dial_code: '+672',
      flag_icon: '/flag-icons/aq.svg',
    },
    {
      name: 'Argentina',
      iso: 'AR',
      dial_code: '+54',
      flag_icon: '/flag-icons/ar.svg',
    },
    {
      name: 'American Samoa',
      iso: 'AS',
      dial_code: '+1',
      flag_icon: '/flag-icons/as.svg',
    },
    {
      name: 'Austria',
      iso: 'AT',
      dial_code: '+43',
      flag_icon: '/flag-icons/at.svg',
    },
    {
      name: 'Australia',
      iso: 'AU',
      dial_code: '+61',
      flag_icon: '/flag-icons/au.svg',
    },
    {
      name: 'Aruba',
      iso: 'AW',
      dial_code: '+297',
      flag_icon: '/flag-icons/aw.svg',
    },
    {
      name: 'Aland Islands',
      iso: 'AX',
      dial_code: '+358',
      flag_icon: '/flag-icons/ax.svg',
    },
    {
      name: 'Azerbaijan',
      iso: 'AZ',
      dial_code: '+994',
      flag_icon: '/flag-icons/az.svg',
    },
    {
      name: 'Bosnia and Herzegovina',
      iso: 'BA',
      dial_code: '+387',
      flag_icon: '/flag-icons/ba.svg',
    },
    {
      name: 'Barbados',
      iso: 'BB',
      dial_code: '+1',
      flag_icon: '/flag-icons/bb.svg',
    },
    {
      name: 'Bangladesh',
      iso: 'BD',
      dial_code: '+880',
      flag_icon: '/flag-icons/bd.svg',
    },
    {
      name: 'Belgium',
      iso: 'BE',
      dial_code: '+32',
      flag_icon: '/flag-icons/be.svg',
    },
    {
      name: 'Burkina Faso',
      iso: 'BF',
      dial_code: '+226',
      flag_icon: '/flag-icons/bf.svg',
    },
    {
      name: 'Bulgaria',
      iso: 'BG',
      dial_code: '+359',
      flag_icon: '/flag-icons/bg.svg',
    },
    {
      name: 'Bahrain',
      iso: 'BH',
      dial_code: '+973',
      flag_icon: '/flag-icons/bh.svg',
    },
    {
      name: 'Burundi',
      iso: 'BI',
      dial_code: '+257',
      flag_icon: '/flag-icons/bi.svg',
    },
    {
      name: 'Benin',
      iso: 'BJ',
      dial_code: '+229',
      flag_icon: '/flag-icons/bj.svg',
    },
    {
      name: 'Saint Barthelemy',
      iso: 'BL',
      dial_code: '+590',
      flag_icon: '/flag-icons/bl.svg',
    },
    {
      name: 'Bermuda',
      iso: 'BM',
      dial_code: '+1',
      flag_icon: '/flag-icons/bm.svg',
    },
    {
      name: 'Brunei',
      iso: 'BN',
      dial_code: '+673',
      flag_icon: '/flag-icons/bn.svg',
    },
    {
      name: 'Bolivia',
      iso: 'BO',
      dial_code: '+591',
      flag_icon: '/flag-icons/bo.svg',
    },
    {
      name: 'Bonaire, Saint Eustatius and Saba',
      iso: 'BQ',
      dial_code: '+599',
      flag_icon: '/flag-icons/bq.svg',
    },
    {
      name: 'Brazil',
      iso: 'BR',
      dial_code: '+55',
      flag_icon: '/flag-icons/br.svg',
    },
    {
      name: 'Bahamas',
      iso: 'BS',
      dial_code: '+1',
      flag_icon: '/flag-icons/bs.svg',
    },
    {
      name: 'Bhutan',
      iso: 'BT',
      dial_code: '+975',
      flag_icon: '/flag-icons/bt.svg',
    },
    {
      name: 'Bouvet Island',
      iso: 'BV',
      dial_code: '+47',
      flag_icon: '/flag-icons/bv.svg',
    },
    {
      name: 'Botswana',
      iso: 'BW',
      dial_code: '+267',
      flag_icon: '/flag-icons/bw.svg',
    },
    {
      name: 'Belarus',
      iso: 'BY',
      dial_code: '+375',
      flag_icon: '/flag-icons/by.svg',
    },
    {
      name: 'Belize',
      iso: 'BZ',
      dial_code: '+501',
      flag_icon: '/flag-icons/bz.svg',
    },
    {
      name: 'Canada',
      iso: 'CA',
      dial_code: '+1',
      flag_icon: '/flag-icons/ca.svg',
    },
    {
      name: 'Cocos Islands',
      iso: 'CC',
      dial_code: '+61',
      flag_icon: '/flag-icons/cc.svg',
    },
    {
      name: 'Democratic Republic of the Congo',
      iso: 'CD',
      dial_code: '+243',
      flag_icon: '/flag-icons/cd.svg',
    },
    {
      name: 'Central African Republic',
      iso: 'CF',
      dial_code: '+236',
      flag_icon: '/flag-icons/cf.svg',
    },
    {
      name: 'Republic of the Congo',
      iso: 'CG',
      dial_code: '+242',
      flag_icon: '/flag-icons/cg.svg',
    },
    {
      name: 'Switzerland',
      iso: 'CH',
      dial_code: '+41',
      flag_icon: '/flag-icons/ch.svg',
    },
    {
      name: 'Ivory Coast',
      iso: 'CI',
      dial_code: '+225',
      flag_icon: '/flag-icons/ci.svg',
    },
    {
      name: 'Cook Islands',
      iso: 'CK',
      dial_code: '+682',
      flag_icon: '/flag-icons/ck.svg',
    },
    {
      name: 'Chile',
      iso: 'CL',
      dial_code: '+56',
      flag_icon: '/flag-icons/cl.svg',
    },
    {
      name: 'Cameroon',
      iso: 'CM',
      dial_code: '+237',
      flag_icon: '/flag-icons/cm.svg',
    },
    {
      name: 'China',
      iso: 'CN',
      dial_code: '+86',
      flag_icon: '/flag-icons/cn.svg',
    },
    {
      name: 'Colombia',
      iso: 'CO',
      dial_code: '+57',
      flag_icon: '/flag-icons/co.svg',
    },
    {
      name: 'Costa Rica',
      iso: 'CR',
      dial_code: '+506',
      flag_icon: '/flag-icons/cr.svg',
    },
    {
      name: 'Cuba',
      iso: 'CU',
      dial_code: '+53',
      flag_icon: '/flag-icons/cu.svg',
    },
    {
      name: 'Cape Verde',
      iso: 'CV',
      dial_code: '+238',
      flag_icon: '/flag-icons/cv.svg',
    },
    {
      name: 'Curacao',
      iso: 'CW',
      dial_code: '+599',
      flag_icon: '/flag-icons/cw.svg',
    },
    {
      name: 'Christmas Island',
      iso: 'CX',
      dial_code: '+61',
      flag_icon: '/flag-icons/cx.svg',
    },
    {
      name: 'Cyprus',
      iso: 'CY',
      dial_code: '+357',
      flag_icon: '/flag-icons/cy.svg',
    },
    {
      name: 'Czech Republic',
      iso: 'CZ',
      dial_code: '+420',
      flag_icon: '/flag-icons/cz.svg',
    },
    {
      name: 'Germany',
      iso: 'DE',
      dial_code: '+49',
      flag_icon: '/flag-icons/de.svg',
    },
    {
      name: 'Djibouti',
      iso: 'DJ',
      dial_code: '+253',
      flag_icon: '/flag-icons/dj.svg',
    },
    {
      name: 'Denmark',
      iso: 'DK',
      dial_code: '+45',
      flag_icon: '/flag-icons/dk.svg',
    },
    {
      name: 'Dominica',
      iso: 'DM',
      dial_code: '+1',
      flag_icon: '/flag-icons/dm.svg',
    },
    {
      name: 'Dominican Republic',
      iso: 'DO',
      dial_code: '+1',
      flag_icon: '/flag-icons/do.svg',
    },
    {
      name: 'Algeria',
      iso: 'DZ',
      dial_code: '+213',
      flag_icon: '/flag-icons/dz.svg',
    },
    {
      name: 'Ecuador',
      iso: 'EC',
      dial_code: '+593',
      flag_icon: '/flag-icons/ec.svg',
    },
    {
      name: 'Estonia',
      iso: 'EE',
      dial_code: '+372',
      flag_icon: '/flag-icons/ee.svg',
    },
    {
      name: 'Egypt',
      iso: 'EG',
      dial_code: '+20',
      flag_icon: '/flag-icons/eg.svg',
    },
    {
      name: 'Western Sahara',
      iso: 'EH',
      dial_code: '+212',
      flag_icon: '/flag-icons/eh.svg',
    },
    {
      name: 'Eritrea',
      iso: 'ER',
      dial_code: '+291',
      flag_icon: '/flag-icons/er.svg',
    },
    {
      name: 'Spain',
      iso: 'ES',
      dial_code: '+34',
      flag_icon: '/flag-icons/es.svg',
    },
    {
      name: 'Ethiopia',
      iso: 'ET',
      dial_code: '+251',
      flag_icon: '/flag-icons/et.svg',
    },
    {
      name: 'Finland',
      iso: 'FI',
      dial_code: '+358',
      flag_icon: '/flag-icons/fi.svg',
    },
    {
      name: 'Fiji',
      iso: 'FJ',
      dial_code: '+679',
      flag_icon: '/flag-icons/fj.svg',
    },
    {
      name: 'Falkland Islands',
      iso: 'FK',
      dial_code: '+500',
      flag_icon: '/flag-icons/fk.svg',
    },
    {
      name: 'Micronesia',
      iso: 'FM',
      dial_code: '+691',
      flag_icon: '/flag-icons/fm.svg',
    },
    {
      name: 'Faroe Islands',
      iso: 'FO',
      dial_code: '+298',
      flag_icon: '/flag-icons/fo.svg',
    },
    {
      name: 'France',
      iso: 'FR',
      dial_code: '+33',
      flag_icon: '/flag-icons/fr.svg',
    },
    {
      name: 'Gabon',
      iso: 'GA',
      dial_code: '+241',
      flag_icon: '/flag-icons/ga.svg',
    },
    {
      name: 'United Kingdom',
      iso: 'GB',
      dial_code: '+44',
      flag_icon: '/flag-icons/gb.svg',
    },
    {
      name: 'Grenada',
      iso: 'GD',
      dial_code: '+1',
      flag_icon: '/flag-icons/gd.svg',
    },
    {
      name: 'Georgia',
      iso: 'GE',
      dial_code: '+995',
      flag_icon: '/flag-icons/ge.svg',
    },
    {
      name: 'French Guiana',
      iso: 'GF',
      dial_code: '+594',
      flag_icon: '/flag-icons/gf.svg',
    },
    {
      name: 'Guernsey',
      iso: 'GG',
      dial_code: '+44',
      flag_icon: '/flag-icons/gg.svg',
    },
    {
      name: 'Ghana',
      iso: 'GH',
      dial_code: '+233',
      flag_icon: '/flag-icons/gh.svg',
    },
    {
      name: 'Gibraltar',
      iso: 'GI',
      dial_code: '+350',
      flag_icon: '/flag-icons/gi.svg',
    },
    {
      name: 'Greenland',
      iso: 'GL',
      dial_code: '+299',
      flag_icon: '/flag-icons/gl.svg',
    },
    {
      name: 'Gambia',
      iso: 'GM',
      dial_code: '+220',
      flag_icon: '/flag-icons/gm.svg',
    },
    {
      name: 'Guinea',
      iso: 'GN',
      dial_code: '+224',
      flag_icon: '/flag-icons/gn.svg',
    },
    {
      name: 'Guadeloupe',
      iso: 'GP',
      dial_code: '+590',
      flag_icon: '/flag-icons/gp.svg',
    },
    {
      name: 'Equatorial Guinea',
      iso: 'GQ',
      dial_code: '+240',
      flag_icon: '/flag-icons/gq.svg',
    },
    {
      name: 'Greece',
      iso: 'GR',
      dial_code: '+30',
      flag_icon: '/flag-icons/gr.svg',
    },
    {
      name: 'South Georgia and the South Sandwich Islands',
      iso: 'GS',
      dial_code: '+500',
      flag_icon: '/flag-icons/gs.svg',
    },
    {
      name: 'Guatemala',
      iso: 'GT',
      dial_code: '+502',
      flag_icon: '/flag-icons/gt.svg',
    },
    {
      name: 'Guam',
      iso: 'GU',
      dial_code: '+1',
      flag_icon: '/flag-icons/gu.svg',
    },
    {
      name: 'Guinea-Bissau',
      iso: 'GW',
      dial_code: '+245',
      flag_icon: '/flag-icons/gw.svg',
    },
    {
      name: 'Guyana',
      iso: 'GY',
      dial_code: '+592',
      flag_icon: '/flag-icons/gy.svg',
    },
    {
      name: 'Hong Kong',
      iso: 'HK',
      dial_code: '+852',
      flag_icon: '/flag-icons/hk.svg',
    },
    {
      name: 'Heard Island and McDonald Islands',
      iso: 'HM',
      dial_code: '+61',
      flag_icon: '/flag-icons/hm.svg',
    },
    {
      name: 'Honduras',
      iso: 'HN',
      dial_code: '+504',
      flag_icon: '/flag-icons/hn.svg',
    },
    {
      name: 'Croatia',
      iso: 'HR',
      dial_code: '+385',
      flag_icon: '/flag-icons/hr.svg',
    },
    {
      name: 'Haiti',
      iso: 'HT',
      dial_code: '+509',
      flag_icon: '/flag-icons/ht.svg',
    },
    {
      name: 'Hungary',
      iso: 'HU',
      dial_code: '+36',
      flag_icon: '/flag-icons/hu.svg',
    },
    {
      name: 'Indonesia',
      iso: 'ID',
      dial_code: '+62',
      flag_icon: '/flag-icons/id.svg',
    },
    {
      name: 'Ireland',
      iso: 'IE',
      dial_code: '+353',
      flag_icon: '/flag-icons/ie.svg',
    },
    {
      name: 'Israel',
      iso: 'IL',
      dial_code: '+972',
      flag_icon: '/flag-icons/il.svg',
    },
    {
      name: 'Isle of Man',
      iso: 'IM',
      dial_code: '+44',
      flag_icon: '/flag-icons/im.svg',
    },
    {
      name: 'India',
      iso: 'IN',
      dial_code: '+91',
      flag_icon: '/flag-icons/in.svg',
    },
    {
      name: 'British Indian Ocean Territory',
      iso: 'IO',
      dial_code: '+246',
      flag_icon: '/flag-icons/io.svg',
    },
    {
      name: 'Iraq',
      iso: 'IQ',
      dial_code: '+964',
      flag_icon: '/flag-icons/iq.svg',
    },
    {
      name: 'Iran',
      iso: 'IR',
      dial_code: '+98',
      flag_icon: '/flag-icons/ir.svg',
    },
    {
      name: 'Iceland',
      iso: 'IS',
      dial_code: '+354',
      flag_icon: '/flag-icons/is.svg',
    },
    {
      name: 'Italy',
      iso: 'IT',
      dial_code: '+39',
      flag_icon: '/flag-icons/it.svg',
    },
    {
      name: 'Jersey',
      iso: 'JE',
      dial_code: '+44',
      flag_icon: '/flag-icons/je.svg',
    },
    {
      name: 'Jamaica',
      iso: 'JM',
      dial_code: '+1',
      flag_icon: '/flag-icons/jm.svg',
    },
    {
      name: 'Jordan',
      iso: 'JO',
      dial_code: '+962',
      flag_icon: '/flag-icons/jo.svg',
    },
    {
      name: 'Japan',
      iso: 'JP',
      dial_code: '+81',
      flag_icon: '/flag-icons/jp.svg',
    },
    {
      name: 'Kenya',
      iso: 'KE',
      dial_code: '+254',
      flag_icon: '/flag-icons/ke.svg',
    },
    {
      name: 'Kyrgyzstan',
      iso: 'KG',
      dial_code: '+996',
      flag_icon: '/flag-icons/kg.svg',
    },
    {
      name: 'Cambodia',
      iso: 'KH',
      dial_code: '+855',
      flag_icon: '/flag-icons/kh.svg',
    },
    {
      name: 'Kiribati',
      iso: 'KI',
      dial_code: '+686',
      flag_icon: '/flag-icons/ki.svg',
    },
    {
      name: 'Comoros',
      iso: 'KM',
      dial_code: '+269',
      flag_icon: '/flag-icons/km.svg',
    },
    {
      name: 'Saint Kitts and Nevis',
      iso: 'KN',
      dial_code: '+1',
      flag_icon: '/flag-icons/kn.svg',
    },
    {
      name: 'North Korea',
      iso: 'KP',
      dial_code: '+850',
      flag_icon: '/flag-icons/kp.svg',
    },
    {
      name: 'South Korea',
      iso: 'KR',
      dial_code: '+82',
      flag_icon: '/flag-icons/kr.svg',
    },
    {
      name: 'Kuwait',
      iso: 'KW',
      dial_code: '+965',
      flag_icon: '/flag-icons/kw.svg',
    },
    {
      name: 'Cayman Islands',
      iso: 'KY',
      dial_code: '+1',
      flag_icon: '/flag-icons/ky.svg',
    },
    {
      name: 'Kazakhstan',
      iso: 'KZ',
      dial_code: '+7',
      flag_icon: '/flag-icons/kz.svg',
    },
    {
      name: 'Laos',
      iso: 'LA',
      dial_code: '+856',
      flag_icon: '/flag-icons/la.svg',
    },
    {
      name: 'Lebanon',
      iso: 'LB',
      dial_code: '+961',
      flag_icon: '/flag-icons/lb.svg',
    },
    {
      name: 'Saint Lucia',
      iso: 'LC',
      dial_code: '+1',
      flag_icon: '/flag-icons/lc.svg',
    },
    {
      name: 'Liechtenstein',
      iso: 'LI',
      dial_code: '+423',
      flag_icon: '/flag-icons/li.svg',
    },
    {
      name: 'Sri Lanka',
      iso: 'LK',
      dial_code: '+94',
      flag_icon: '/flag-icons/lk.svg',
    },
    {
      name: 'Liberia',
      iso: 'LR',
      dial_code: '+231',
      flag_icon: '/flag-icons/lr.svg',
    },
    {
      name: 'Lesotho',
      iso: 'LS',
      dial_code: '+266',
      flag_icon: '/flag-icons/ls.svg',
    },
    {
      name: 'Lithuania',
      iso: 'LT',
      dial_code: '+370',
      flag_icon: '/flag-icons/lt.svg',
    },
    {
      name: 'Luxembourg',
      iso: 'LU',
      dial_code: '+352',
      flag_icon: '/flag-icons/lu.svg',
    },
    {
      name: 'Latvia',
      iso: 'LV',
      dial_code: '+371',
      flag_icon: '/flag-icons/lv.svg',
    },
    {
      name: 'Libya',
      iso: 'LY',
      dial_code: '+218',
      flag_icon: '/flag-icons/ly.svg',
    },
    {
      name: 'Morocco',
      iso: 'MA',
      dial_code: '+212',
      flag_icon: '/flag-icons/ma.svg',
    },
    {
      name: 'Monaco',
      iso: 'MC',
      dial_code: '+377',
      flag_icon: '/flag-icons/mc.svg',
    },
    {
      name: 'Moldova',
      iso: 'MD',
      dial_code: '+373',
      flag_icon: '/flag-icons/md.svg',
    },
    {
      name: 'Montenegro',
      iso: 'ME',
      dial_code: '+382',
      flag_icon: '/flag-icons/me.svg',
    },
    {
      name: 'Saint Martin',
      iso: 'MF',
      dial_code: '+590',
      flag_icon: '/flag-icons/mf.svg',
    },
    {
      name: 'Madagascar',
      iso: 'MG',
      dial_code: '+261',
      flag_icon: '/flag-icons/mg.svg',
    },
    {
      name: 'Marshall Islands',
      iso: 'MH',
      dial_code: '+692',
      flag_icon: '/flag-icons/mh.svg',
    },
    {
      name: 'Macedonia',
      iso: 'MK',
      dial_code: '+389',
      flag_icon: '/flag-icons/mk.svg',
    },
    {
      name: 'Mali',
      iso: 'ML',
      dial_code: '+223',
      flag_icon: '/flag-icons/ml.svg',
    },
    {
      name: 'Myanmar',
      iso: 'MM',
      dial_code: '+95',
      flag_icon: '/flag-icons/mm.svg',
    },
    {
      name: 'Mongolia',
      iso: 'MN',
      dial_code: '+976',
      flag_icon: '/flag-icons/mn.svg',
    },
    {
      name: 'Macao',
      iso: 'MO',
      dial_code: '+853',
      flag_icon: '/flag-icons/mo.svg',
    },
    {
      name: 'Northern Mariana Islands',
      iso: 'MP',
      dial_code: '+1',
      flag_icon: '/flag-icons/mp.svg',
    },
    {
      name: 'Martinique',
      iso: 'MQ',
      dial_code: '+596',
      flag_icon: '/flag-icons/mq.svg',
    },
    {
      name: 'Mauritania',
      iso: 'MR',
      dial_code: '+222',
      flag_icon: '/flag-icons/mr.svg',
    },
    {
      name: 'Montserrat',
      iso: 'MS',
      dial_code: '+1',
      flag_icon: '/flag-icons/ms.svg',
    },
    {
      name: 'Malta',
      iso: 'MT',
      dial_code: '+356',
      flag_icon: '/flag-icons/mt.svg',
    },
    {
      name: 'Mauritius',
      iso: 'MU',
      dial_code: '+230',
      flag_icon: '/flag-icons/mu.svg',
    },
    {
      name: 'Maldives',
      iso: 'MV',
      dial_code: '+960',
      flag_icon: '/flag-icons/mv.svg',
    },
    {
      name: 'Malawi',
      iso: 'MW',
      dial_code: '+265',
      flag_icon: '/flag-icons/mw.svg',
    },
    {
      name: 'Mexico',
      iso: 'MX',
      dial_code: '+52',
      flag_icon: '/flag-icons/mx.svg',
    },
    {
      name: 'Malaysia',
      iso: 'MY',
      dial_code: '+60',
      flag_icon: '/flag-icons/my.svg',
    },
    {
      name: 'Mozambique',
      iso: 'MZ',
      dial_code: '+258',
      flag_icon: '/flag-icons/mz.svg',
    },
    {
      name: 'Namibia',
      iso: 'NA',
      dial_code: '+264',
      flag_icon: '/flag-icons/na.svg',
    },
    {
      name: 'New Caledonia',
      iso: 'NC',
      dial_code: '+687',
      flag_icon: '/flag-icons/nc.svg',
    },
    {
      name: 'Niger',
      iso: 'NE',
      dial_code: '+227',
      flag_icon: '/flag-icons/ne.svg',
    },
    {
      name: 'Norfolk Island',
      iso: 'NF',
      dial_code: '+672',
      flag_icon: '/flag-icons/nf.svg',
    },
    {
      name: 'Nigeria',
      iso: 'NG',
      dial_code: '+234',
      flag_icon: '/flag-icons/ng.svg',
    },
    {
      name: 'Nicaragua',
      iso: 'NI',
      dial_code: '+505',
      flag_icon: '/flag-icons/ni.svg',
    },
    {
      name: 'Netherlands',
      iso: 'NL',
      dial_code: '+31',
      flag_icon: '/flag-icons/nl.svg',
    },
    {
      name: 'Norway',
      iso: 'NO',
      dial_code: '+47',
      flag_icon: '/flag-icons/no.svg',
    },
    {
      name: 'Nepal',
      iso: 'NP',
      dial_code: '+977',
      flag_icon: '/flag-icons/np.svg',
    },
    {
      name: 'Nauru',
      iso: 'NR',
      dial_code: '+674',
      flag_icon: '/flag-icons/nr.svg',
    },
    {
      name: 'Niue',
      iso: 'NU',
      dial_code: '+683',
      flag_icon: '/flag-icons/nu.svg',
    },
    {
      name: 'New Zealand',
      iso: 'NZ',
      dial_code: '+64',
      flag_icon: '/flag-icons/nz.svg',
    },
    {
      name: 'Oman',
      iso: 'OM',
      dial_code: '+968',
      flag_icon: '/flag-icons/om.svg',
    },
    {
      name: 'Panama',
      iso: 'PA',
      dial_code: '+507',
      flag_icon: '/flag-icons/pa.svg',
    },
    {
      name: 'Peru',
      iso: 'PE',
      dial_code: '+51',
      flag_icon: '/flag-icons/pe.svg',
    },
    {
      name: 'French Polynesia',
      iso: 'PF',
      dial_code: '+689',
      flag_icon: '/flag-icons/pf.svg',
    },
    {
      name: 'Papua New Guinea',
      iso: 'PG',
      dial_code: '+675',
      flag_icon: '/flag-icons/pg.svg',
    },
    {
      name: 'Philippines',
      iso: 'PH',
      dial_code: '+63',
      flag_icon: '/flag-icons/ph.svg',
    },
    {
      name: 'Pakistan',
      iso: 'PK',
      dial_code: '+92',
      flag_icon: '/flag-icons/pk.svg',
    },
    {
      name: 'Poland',
      iso: 'PL',
      dial_code: '+48',
      flag_icon: '/flag-icons/pl.svg',
    },
    {
      name: 'Saint Pierre and Miquelon',
      iso: 'PM',
      dial_code: '+508',
      flag_icon: '/flag-icons/pm.svg',
    },
    {
      name: 'Pitcairn',
      iso: 'PN',
      dial_code: '+870',
      flag_icon: '/flag-icons/pn.svg',
    },
    {
      name: 'Puerto Rico',
      iso: 'PR',
      dial_code: '+1',
      flag_icon: '/flag-icons/pr.svg',
    },
    {
      name: 'Palestinian Territory',
      iso: 'PS',
      dial_code: '+970',
      flag_icon: '/flag-icons/ps.svg',
    },
    {
      name: 'Portugal',
      iso: 'PT',
      dial_code: '+351',
      flag_icon: '/flag-icons/pt.svg',
    },
    {
      name: 'Palau',
      iso: 'PW',
      dial_code: '+680',
      flag_icon: '/flag-icons/pw.svg',
    },
    {
      name: 'Paraguay',
      iso: 'PY',
      dial_code: '+595',
      flag_icon: '/flag-icons/py.svg',
    },
    {
      name: 'Qatar',
      iso: 'QA',
      dial_code: '+974',
      flag_icon: '/flag-icons/qa.svg',
    },
    {
      name: 'Reunion',
      iso: 'RE',
      dial_code: '+262',
      flag_icon: '/flag-icons/re.svg',
    },
    {
      name: 'Romania',
      iso: 'RO',
      dial_code: '+40',
      flag_icon: '/flag-icons/ro.svg',
    },
    {
      name: 'Serbia',
      iso: 'RS',
      dial_code: '+381',
      flag_icon: '/flag-icons/rs.svg',
    },
    {
      name: 'Russia',
      iso: 'RU',
      dial_code: '+7',
      flag_icon: '/flag-icons/ru.svg',
    },
    {
      name: 'Rwanda',
      iso: 'RW',
      dial_code: '+250',
      flag_icon: '/flag-icons/rw.svg',
    },
    {
      name: 'Saudi Arabia',
      iso: 'SA',
      dial_code: '+966',
      flag_icon: '/flag-icons/sa.svg',
    },
    {
      name: 'Solomon Islands',
      iso: 'SB',
      dial_code: '+677',
      flag_icon: '/flag-icons/sb.svg',
    },
    {
      name: 'Seychelles',
      iso: 'SC',
      dial_code: '+248',
      flag_icon: '/flag-icons/sc.svg',
    },
    {
      name: 'Sudan',
      iso: 'SD',
      dial_code: '+249',
      flag_icon: '/flag-icons/sd.svg',
    },
    {
      name: 'Sweden',
      iso: 'SE',
      dial_code: '+46',
      flag_icon: '/flag-icons/se.svg',
    },
    {
      name: 'Singapore',
      iso: 'SG',
      dial_code: '+65',
      flag_icon: '/flag-icons/sg.svg',
    },
    {
      name: 'Saint Helena',
      iso: 'SH',
      dial_code: '+290',
      flag_icon: '/flag-icons/sh.svg',
    },
    {
      name: 'Slovenia',
      iso: 'SI',
      dial_code: '+386',
      flag_icon: '/flag-icons/si.svg',
    },
    {
      name: 'Svalbard and Jan Mayen',
      iso: 'SJ',
      dial_code: '+47',
      flag_icon: '/flag-icons/sj.svg',
    },
    {
      name: 'Slovakia',
      iso: 'SK',
      dial_code: '+421',
      flag_icon: '/flag-icons/sk.svg',
    },
    {
      name: 'Sierra Leone',
      iso: 'SL',
      dial_code: '+232',
      flag_icon: '/flag-icons/sl.svg',
    },
    {
      name: 'San Marino',
      iso: 'SM',
      dial_code: '+378',
      flag_icon: '/flag-icons/sm.svg',
    },
    {
      name: 'Senegal',
      iso: 'SN',
      dial_code: '+221',
      flag_icon: '/flag-icons/sn.svg',
    },
    {
      name: 'Somalia',
      iso: 'SO',
      dial_code: '+252',
      flag_icon: '/flag-icons/so.svg',
    },
    {
      name: 'Suriname',
      iso: 'SR',
      dial_code: '+597',
      flag_icon: '/flag-icons/sr.svg',
    },
    {
      name: 'South Sudan',
      iso: 'SS',
      dial_code: '+211',
      flag_icon: '/flag-icons/ss.svg',
    },
    {
      name: 'Sao Tome and Principe',
      iso: 'ST',
      dial_code: '+239',
      flag_icon: '/flag-icons/st.svg',
    },
    {
      name: 'El Salvador',
      iso: 'SV',
      dial_code: '+503',
      flag_icon: '/flag-icons/sv.svg',
    },
    {
      name: 'Sint Maarten',
      iso: 'SX',
      dial_code: '+599',
      flag_icon: '/flag-icons/sx.svg',
    },
    {
      name: 'Syria',
      iso: 'SY',
      dial_code: '+963',
      flag_icon: '/flag-icons/sy.svg',
    },
    {
      name: 'Swaziland',
      iso: 'SZ',
      dial_code: '+268',
      flag_icon: '/flag-icons/sz.svg',
    },
    {
      name: 'Turks and Caicos Islands',
      iso: 'TC',
      dial_code: '+1',
      flag_icon: '/flag-icons/tc.svg',
    },
    {
      name: 'Chad',
      iso: 'TD',
      dial_code: '+235',
      flag_icon: '/flag-icons/td.svg',
    },
    {
      name: 'French Southern Territories',
      iso: 'TF',
      dial_code: '+262',
      flag_icon: '/flag-icons/tf.svg',
    },
    {
      name: 'Togo',
      iso: 'TG',
      dial_code: '+228',
      flag_icon: '/flag-icons/tg.svg',
    },
    {
      name: 'Thailand',
      iso: 'TH',
      dial_code: '+66',
      flag_icon: '/flag-icons/th.svg',
    },
    {
      name: 'Tajikistan',
      iso: 'TJ',
      dial_code: '+992',
      flag_icon: '/flag-icons/tj.svg',
    },
    {
      name: 'Tokelau',
      iso: 'TK',
      dial_code: '+690',
      flag_icon: '/flag-icons/tk.svg',
    },
    {
      name: 'East Timor',
      iso: 'TL',
      dial_code: '+670',
      flag_icon: '/flag-icons/tl.svg',
    },
    {
      name: 'Turkmenistan',
      iso: 'TM',
      dial_code: '+993',
      flag_icon: '/flag-icons/tm.svg',
    },
    {
      name: 'Tunisia',
      iso: 'TN',
      dial_code: '+216',
      flag_icon: '/flag-icons/tn.svg',
    },
    {
      name: 'Tonga',
      iso: 'TO',
      dial_code: '+676',
      flag_icon: '/flag-icons/to.svg',
    },
    {
      name: 'Turkey',
      iso: 'TR',
      dial_code: '+90',
      flag_icon: '/flag-icons/tr.svg',
    },
    {
      name: 'Trinidad and Tobago',
      iso: 'TT',
      dial_code: '+1',
      flag_icon: '/flag-icons/tt.svg',
    },
    {
      name: 'Tuvalu',
      iso: 'TV',
      dial_code: '+688',
      flag_icon: '/flag-icons/tv.svg',
    },
    {
      name: 'Taiwan',
      iso: 'TW',
      dial_code: '+886',
      flag_icon: '/flag-icons/tw.svg',
    },
    {
      name: 'Tanzania',
      iso: 'TZ',
      dial_code: '+255',
      flag_icon: '/flag-icons/tz.svg',
    },
    {
      name: 'Ukraine',
      iso: 'UA',
      dial_code: '+380',
      flag_icon: '/flag-icons/ua.svg',
    },
    {
      name: 'Uganda',
      iso: 'UG',
      dial_code: '+256',
      flag_icon: '/flag-icons/ug.svg',
    },
    {
      name: 'United States Minor Outlying Islands',
      iso: 'UM',
      dial_code: '+1',
      flag_icon: '/flag-icons/um.svg',
    },
    {
      name: 'United States',
      iso: 'US',
      dial_code: '+1',
      flag_icon: '/flag-icons/us.svg',
    },
    {
      name: 'Uruguay',
      iso: 'UY',
      dial_code: '+598',
      flag_icon: '/flag-icons/uy.svg',
    },
    {
      name: 'Uzbekistan',
      iso: 'UZ',
      dial_code: '+998',
      flag_icon: '/flag-icons/uz.svg',
    },
    {
      name: 'Vatican',
      iso: 'VA',
      dial_code: '+379',
      flag_icon: '/flag-icons/va.svg',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      iso: 'VC',
      dial_code: '+1',
      flag_icon: '/flag-icons/vc.svg',
    },
    {
      name: 'Venezuela',
      iso: 'VE',
      dial_code: '+58',
      flag_icon: '/flag-icons/ve.svg',
    },
    {
      name: 'British Virgin Islands',
      iso: 'VG',
      dial_code: '+1',
      flag_icon: '/flag-icons/vg.svg',
    },
    {
      name: 'U.S. Virgin Islands',
      iso: 'VI',
      dial_code: '+1',
      flag_icon: '/flag-icons/vi.svg',
    },
    {
      name: 'Vietnam',
      iso: 'VN',
      dial_code: '+84',
      flag_icon: '/flag-icons/vn.svg',
    },
    {
      name: 'Vanuatu',
      iso: 'VU',
      dial_code: '+678',
      flag_icon: '/flag-icons/vu.svg',
    },
    {
      name: 'Wallis and Futuna',
      iso: 'WF',
      dial_code: '+681',
      flag_icon: '/flag-icons/wf.svg',
    },
    {
      name: 'Samoa',
      iso: 'WS',
      dial_code: '+685',
      flag_icon: '/flag-icons/ws.svg',
    },
    {
      name: 'Kosovo',
      iso: 'XK',
      dial_code: '+383',
      flag_icon: '/flag-icons/xk.svg',
    },
    {
      name: 'Yemen',
      iso: 'YE',
      dial_code: '+967',
      flag_icon: '/flag-icons/ye.svg',
    },
    {
      name: 'Mayotte',
      iso: 'YT',
      dial_code: '+262',
      flag_icon: '/flag-icons/yt.svg',
    },
    {
      name: 'South Africa',
      iso: 'ZA',
      dial_code: '+27',
      flag_icon: '/flag-icons/za.svg',
    },
    {
      name: 'Zambia',
      iso: 'ZM',
      dial_code: '+260',
      flag_icon: '/flag-icons/zm.svg',
    },
    {
      name: 'Zimbabwe',
      iso: 'ZW',
      dial_code: '+263',
      flag_icon: '/flag-icons/zw.svg',
    },
  ];
};
